---

- name: "install vagrant on debian and ubuntu"
  apt:
    deb: "{{ vagrant_url_deb }}"
  when: ansible_facts['os_family'] == "Debian"

- name: "install vagramt on rpm based systems"
  yum:
    name: "{{ vagrant_url_rpm }}"
  when: ansible_facts['os_family'] == "RedHat"