---

- name: "install kata container repo key"
  apt_key:
    url: "{{ kata_key }}"
    state: present

- name: "add kata container repo"
  apt_repository:
    repo: "{{ kata_repo }}"
    state: present
    filename: kata-containers.list

- name: "install kata container packages"
  apt:
    name: "{{ kata_pkgs }}"
    state: present
    update_cache: yes

- name: "check if docker is installed"
  stat:
    path: "{{ docker_path }}"
  register: docker

- name: "create system.d dir for docker"
  file:
    path: "/etc/systemd/system/docker.service.d/"
    state: directory
    mode: 0755
    owner: root
    group: root
  when: docker.stat.exists

- name: "deploy systemd file"
  template:
    src: kata-containers.conf
    dest: /etc/systemd/system/docker.service.d/kata-containers.conf
    mode: 0644
    owner: root
    group: root

- name: "reload daemon"
  systemd:
    daemon_reload: yes
    name: docker.service

- name: "restart docker"
  systemd:
    name: docker.service
    enabled: yes
    state: restarted

  
