---

- name: "install vscodium repo key"
  apt_key:
    url: "{{ vscodium_key }}"
    state: present

- name: "add vscodium repo"
  apt_repository:
    repo: "{{ vscodium_repo }}"
    state: present
    filename: kata-containers.list

- name: "install vscodium packages"
  apt:
    name: "{{ vscodium_pkgs }}"
    state: present
    update_cache: yes