---

- name: "install require packages"
  apt:
    name: "{{ required_pkgs }}"
    state: present
    update_cache: yes

- name: "install docker repo key"
  apt_key:
    id: "{{ docker_repo_key_id }}"
    url: "{{ docker_repo_key }}"
    state: present

- name: "add docker repo"
  apt_repository:
    repo: "{{ docker_repo }}"
    state: present
    filename: docker-ce.list

- name: "install docker-ce packages"
  apt:
    name: "{{ docker_version }}"
    state: present
    update_cache: yes