---

- name: "install enpass repo key"
  apt_key:
    url: "{{ enpass_key }}"
    state: present

- name: "add enpass repo"
  apt_repository:
    repo: "{{ enpass_repo }}"
    state: present
    filename: kata-containers.list

- name: "install enpass packages"
  apt:
    name: "{{ enpass_pkgs }}"
    state: present
    update_cache: yes